// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
public partial class MLModel
{
    /// <summary>
    /// model input class for MLModel.
    /// </summary>
    #region model input class
    public class ModelInput
    {
        [LoadColumn(4)]
        [ColumnName(@"stars")]
        public float Stars { get; set; }

        [LoadColumn(5)]
        [ColumnName(@"reviews")]
        public float Reviews { get; set; }

        [LoadColumn(6)]
        [ColumnName(@"price")]
        public float Price { get; set; }

        [LoadColumn(7)]
        [ColumnName(@"listPrice")]
        public float ListPrice { get; set; }

        [LoadColumn(8)]
        [ColumnName(@"category_id")]
        public float Category_id { get; set; }

        [LoadColumn(9)]
        [ColumnName(@"isBestSeller")]
        public bool IsBestSeller { get; set; }

        [LoadColumn(10)]
        [ColumnName(@"boughtInLastMonth")]
        public float BoughtInLastMonth { get; set; }

    }

    #endregion

    /// <summary>
    /// model output class for MLModel.
    /// </summary>
    #region model output class
    public class ModelOutput
    {
        [ColumnName(@"stars")]
        public float Stars { get; set; }

        [ColumnName(@"reviews")]
        public float Reviews { get; set; }

        [ColumnName(@"price")]
        public float Price { get; set; }

        [ColumnName(@"listPrice")]
        public float ListPrice { get; set; }

        [ColumnName(@"category_id")]
        public float Category_id { get; set; }

        [ColumnName(@"isBestSeller")]
        public bool IsBestSeller { get; set; }

        [ColumnName(@"boughtInLastMonth")]
        public float BoughtInLastMonth { get; set; }

        [ColumnName(@"Features")]
        public float[] Features { get; set; }

        [ColumnName(@"PredictedLabel")]
        public bool PredictedLabel { get; set; }

        [ColumnName(@"Score")]
        public float Score { get; set; }

        [ColumnName(@"Probability")]
        public float Probability { get; set; }

    }

    #endregion

    private static string MLNetModelPath = Path.GetFullPath("MLModel.mlnet");

    public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


    private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
    {
        var mlContext = new MLContext();
        ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
        return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
    }

    /// <summary>
    /// Use this method to predict on <see cref="ModelInput"/>.
    /// </summary>
    /// <param name="input">model input.</param>
    /// <returns><seealso cref=" ModelOutput"/></returns>
    public static ModelOutput Predict(ModelInput input)
    {
        var predEngine = PredictEngine.Value;
        return predEngine.Predict(input);
    }

}
